project_id = "yxtnzigvmjlwherdasyk"

[functions.ai-chatbot]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.upload-whatsapp-media]
verify_jwt = true